In [1]:
!python -m pip install numpy

In [2]:
import numpy as np

# numpy를 쓰는 이유

-일반 리스트로 계산하면

num_list = [1, 2, 3, 4]

num_list * 2  →  [1, 2, 3, 4, 1, 2, 3, 4]  # 리스트가 복사됨 ❌

-numpy 배열로 계산하면
int_arr2 = np.array([1, 2, 3, 4])

int_arr2 * 2  →  [2, 4, 6, 8]  # 각 숫자에 2를 곱함 ✅

1차원 -> 일렬로 세운 계란 한줄 / 그냥 줄 하나
2차원 -> 계란판(가로,세로) / 표 형태(엑셀처럼)
3차원 -> 계란판이 여러 장 쌓인 것 / 표가 여러 장

ai/데이터분석에서 중요한 이유는?

    (높이,너비,색상)-이미지한장(3차원) -> (28,28,3)
    (날짜, 종목) - 주가 데이터(2차원) -> (365,100)

In [ ]:
num_list=[1,2,3,4]      #파이썬 일반 리스트
int_arr2 = np.array(num_list)       #numpy 배열로 변환/ array()는 이미있는 데이터를 numpy배열로 변환 시키는거
print(int_arr2)     #[1,2,3,4] 출력

[1 2 3 4]


In [14]:
arr1 = np.arange(0,10)      #일반리스트의 range()와 같아보이지만 바로 수학계산이 가능
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2 = np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

In [15]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [ ]:
list_data1 = [1, '2', 3]
arr4 = np.array(list_data1)
arr4
#numpy는 배열 안의 모든 데이터 타입을 하나로 통일시키는 특징이 있어서 결국 전부 문자열로 변환

array(['1', '2', '3'], dtype='<U21')

In [17]:
list_data2 = [1,2,3]
arr5 = np.array(list_data2)
arr5

array([1, 2, 3])

In [ ]:
temp6 = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]    #리스트 안에 리스트가 있는 구조
arr6 = np.array(temp6)
print(arr6)         #줄이 여러개 이므로 표 형태로 만들어짐.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(temp6)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [20]:
print(type(temp6))
print(type(arr6))

<class 'list'>
<class 'numpy.ndarray'>


In [22]:
arr7 = np.array([
                    [[1,2,3,4], [5,6,7,8]],
                    [[9,10,11,12], [13,14,15,16]],
                    [[17,18,19,20], [21,22,23,34]]
                ])
print(arr7)
print(type(arr7))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 34]]]
<class 'numpy.ndarray'>


In [ ]:
arr8 = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr8.ndim)        #몇 차원인지 숫자 하나로 알려줌
print(arr8.shape)       #전체 구조를 알려줌 / 차원이 늘어날수록 숫자가 하나씩 추가

#arr8은 1차원이자 10개짜리를 2행 5열로 모양을 변경
arr9 = arr8.reshape(2,5)    

print(arr9.ndim)
print(arr9.shape)

1
(10,)
2
(2, 5)


In [27]:
print(arr8)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
print(arr9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
arr8.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [30]:
arr10 = arr8.reshape(2, 5, 1)

print(arr10.ndim)
print(arr10.shape)
print(arr10)

# (2, 5) 의 shape
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]]

3
(2, 5, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


# shape

(2, 5) 와 (2, 5, 1) 은 전혀 다른 numpy array 이다.  
(10, ) 와 (10, 1) 은 전혀 다른 numpy array 이다.

In [ ]:
arr11 = np.linspace(1, 10, 10)      #1부터 10까지 균등하게 10개 실수

print(arr11)
print(arr11.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [ ]:
arr12 = np.linspace(1, 10, 10, dtype=int) #정수로 강제 변환 시킴

print(arr12)
print(arr12.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
int64


In [ ]:
arr13 = np.linspace(0, 10, 10)  #0부터 10까지 10개 / 0부터 10까지 간격을 10개로 나누면 안떨어짐

print(arr13)
print(arr13.dtype)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
float64


In [ ]:
arr14 = np.zeros(10)        #10개짜리 0으로 채워진 배열을 만들라는 내용
print(arr14)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
data1 = list(range(0, 10))

data2 = []
for x in data1:
    data2.append(x*2)

data3 = [x*2 for x in data1]        #리스트 컴프리헨션(한 줄로 압축한 방식)

print(data1)
print(data2)
print(data3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [36]:
data4 = np.array(data1)
data5 = 2 * data4
print(data5)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
data5.dtype #정수라는거고, 64는 컴퓨터가 64비트체제니까 나오는거

dtype('int64')

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print(a == 2)       #a의 각 요소가 2인지 아닌지 확인(중간이 2이기 때문에 중간이 True)
print(b > 10)       #b의 각 요소가 10보다 큰지 확인
print((a == 2) & (b > 10))      #둘 다 True인 것만 True

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [39]:
c = np.array([[0, 1, 2], [3, 4, 5]])
d = np.array([
                [
                    [1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]
                 ],
                [
                    [11, 12, 13, 14],
                    [15, 16, 17, 18],
                    [19, 20, 21, 22]
                 ]
             ])

In [ ]:
print(c.ndim, c.shape, c.size)      #2차원, 2행 3열, 전체 요소 개수
print(c)

2 (2, 3) 6
[[0 1 2]
 [3 4 5]]


In [ ]:
print(d.ndim, d.shape, d.size)      #2판 3행 4열
print(d)

3 (2, 3, 4) 24
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [ ]:
f = np.array([10, 11, 12, 13, 14])
print(f[2])     #2번 인덱스인 3번째 값인 12번을 출력
print(f[-1])    #-1번인 인덱스이므로 맨 마지막 값인 14 출력

12
14


In [43]:
g = np.array([[0, 1, 2], [3, 4, 5]])
print(g)

[[0 1 2]
 [3 4 5]]


In [44]:
g[0]

array([0, 1, 2])

In [45]:
print(g[0][0], g[0][1])

0 1


In [46]:
print(g[1][-1])

5


In [47]:
print(g[0, 1])

1


In [ ]:
#      0열  1열  2열
#0행 [  0,  1,   2  ]
#1열 [  3,  4,   5  ]

#g[ : , 1 ]  뜻은?
# 앞은 행 선택이고, 뒤에는 열 선택 (행, 열) / : 은 모든 행 다 가져오라는 거
# 한마디로 (모든 행의, 1번 열만 가져오라는 뜻)

In [51]:
# [[0 1 2]
#  [3 4 5]]

# g[?, ?] = g[?][?]
print(g[:, 1])

[1 4]


In [52]:
h = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(h[:, 1])

[1 5]


In [54]:
#(2,)    →  숫자가 1개 → 1차원 (2개짜리)
#(2, 3)  →  숫자가 2개 → 2차원 (2행 3열)
#(2,3,4) →  숫자가 3개 → 3차원 (2판 3행 4열)

In [ ]:
(h[:, 1]).shape  #모든 행의 1번 열은 [1, 5]인데 그 배열의 구조는? (2,) 2개짜리 1차원

(2,)

In [ ]:
#[행 선택, 열 선택]
#[1번 행, 1번 열부터 4번 열 직전까지]
# 1번 행의 1열부터 3열까지 출력
print(h[1, 1:4])

[5 6 7]


In [56]:
print(h[:, :2])

[[0 1]
 [4 5]]


In [58]:
i = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#각 위치마다 가져올지 말지를 T/F로 표시한 것
ix = np.array([True, False, True, False, True,      
               False, True, False, True, False])
i[ix]

array([0, 2, 4, 6, 8])

In [ ]:
# ==이 있으면 무조건 True/False가 나온다
temp7 = i % 2 == 0      #짝수인지 홀수인지를 True/False로 표시한것
print(temp7.shape)      #True = 0 / False = 1
print(temp7)

(10,)
[ True False  True False  True False  True False  True False]


In [ ]:
i[temp7]    #true/false를 필터로 써서 i에서 값을 꺼내는 것

array([0, 2, 4, 6, 8])

In [ ]:
i[i % 2 == 0]       #i에서 True인 자리 값만 꺼내기

array([0, 2, 4, 6, 8])

In [ ]:
j = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(j[:, [0, 3]])     #0번 열이랑 3번 열만!

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [ ]:
j % 4 == 0 #4로 나눴는데 나머지가 0이 아닌 애들, 4의 배수만 True

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [ ]:
j % 4 == 1      #4로 나눴는데 나머지가 1인 애들, 나눈 후 나머지가 1인 얘들만 True

array([[ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [ ]:
(j % 4 == 0) | (j % 4 == 1)
# |은 둘 중 하나만 true여도 True(or)
# 나머지가 0인 것이거나 나머지가 1인 것에 하나라도 해당하면 True

array([[ True, False, False,  True],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [ ]:
j[(j % 4 == 0) | (j % 4 == 1)]
#위에서 True인 애들만 출력

array([ 1,  4,  5,  8,  9, 12])

In [ ]:
j[[2, 0, 1]]        #2번 행, 0번 행, 1번 행 순서로 가져오라는 코드 

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [69]:
k = np.array(range(1, 21))
print(k)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [70]:
k[k % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [71]:
k[k % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [ ]:
k[(k % 3 == 0) & (k % 4 == 1)]
# &는 둘 다 만족을 해야 True
# 3의 배수이자 4로 나눴을때 나머지가 1인 애만 출력

array([9])